"""Initial schema: flights, append-only observations, events and statistics.

Revision ID: 4539e72de689
Revises: 
Create Date: 2026-09-06 07:31:23.053763+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airlines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('iata', sa.String(length=3), nullable=True),
    sa.Column('icao', sa.String(length=4), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_airlines'))
    )
    op.create_index(op.f('ix_airlines_iata'), 'airlines', ['iata'], unique=True)
    op.create_index(op.f('ix_airlines_icao'), 'airlines', ['icao'], unique=False)
    op.create_table('airports',
    sa.Column('iata', sa.String(length=3), nullable=False),
    sa.Column('icao', sa.String(length=4), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('iata', name=op.f('pk_airports'))
    )
    op.create_index(op.f('ix_airports_icao'), 'airports', ['icao'], unique=False)
    op.create_table('collection_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=True),
    sa.Column('providers_attempted', sa.String(length=200), nullable=True),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.Column('flights_seen', sa.Integer(), nullable=False),
    sa.Column('flights_created', sa.Integer(), nullable=False),
    sa.Column('flights_updated', sa.Integer(), nullable=False),
    sa.Column('observations_written', sa.Integer(), nullable=False),
    sa.Column('events_written', sa.Integer(), nullable=False),
    sa.Column('cancellations_detected', sa.Integer(), nullable=False),
    sa.Column('delays_detected', sa.Integer(), nullable=False),
    sa.Column('stale_marked', sa.Integer(), nullable=False),
    sa.Column('duplicates_skipped', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collection_runs'))
    )
    op.create_index('ix_runs_started', 'collection_runs', ['started_at'], unique=False)
    op.create_table('daily_statistics',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('scope', sa.Enum('OVERALL', 'ROUTE', 'AIRLINE', 'FLIGHT', 'PERIOD', 'DOW', 'ROUTE_PERIOD', 'ROUTE_AIRLINE', name='stat_scope'), nullable=False),
    sa.Column('scope_key', sa.String(length=40), nullable=False),
    sa.Column('route', sa.String(length=8), nullable=True),
    sa.Column('total_flights', sa.Integer(), nullable=False),
    sa.Column('completed_flights', sa.Integer(), nullable=False),
    sa.Column('cancelled_flights', sa.Integer(), nullable=False),
    sa.Column('diverted_flights', sa.Integer(), nullable=False),
    sa.Column('delayed_flights', sa.Integer(), nullable=False),
    sa.Column('on_time_flights', sa.Integer(), nullable=False),
    sa.Column('unknown_flights', sa.Integer(), nullable=False),
    sa.Column('delayed_gt_15', sa.Integer(), nullable=False),
    sa.Column('delayed_gt_30', sa.Integer(), nullable=False),
    sa.Column('delayed_gt_60', sa.Integer(), nullable=False),
    sa.Column('delayed_gt_120', sa.Integer(), nullable=False),
    sa.Column('avg_delay_minutes', sa.Float(), nullable=True),
    sa.Column('median_delay_minutes', sa.Float(), nullable=True),
    sa.Column('p90_delay_minutes', sa.Float(), nullable=True),
    sa.Column('max_delay_minutes', sa.Integer(), nullable=True),
    sa.Column('cancellation_rate', sa.Float(), nullable=True),
    sa.Column('delay_rate', sa.Float(), nullable=True),
    sa.Column('on_time_rate', sa.Float(), nullable=True),
    sa.Column('severe_delay_rate', sa.Float(), nullable=True),
    sa.Column('reliability_score', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_statistics')),
    sa.UniqueConstraint('stat_date', 'scope', 'scope_key', name='uq_daily_stat_dimension')
    )
    op.create_index('ix_daily_date', 'daily_statistics', ['stat_date'], unique=False)
    op.create_index('ix_daily_route', 'daily_statistics', ['route'], unique=False)
    op.create_index('ix_daily_scope_date', 'daily_statistics', ['scope', 'scope_key', 'stat_date'], unique=False)
    op.create_table('flights',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('flight_number', sa.String(length=10), nullable=False),
    sa.Column('flight_iata', sa.String(length=10), nullable=True),
    sa.Column('flight_icao', sa.String(length=10), nullable=True),
    sa.Column('airline_iata', sa.String(length=3), nullable=True),
    sa.Column('airline_icao', sa.String(length=4), nullable=True),
    sa.Column('airline_name', sa.String(length=160), nullable=True),
    sa.Column('origin_iata', sa.String(length=3), nullable=False),
    sa.Column('destination_iata', sa.String(length=3), nullable=False),
    sa.Column('scheduled_departure_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('flight_date_local', sa.Date(), nullable=False),
    sa.Column('scheduled_hour_local', sa.SmallInteger(), nullable=False),
    sa.Column('scheduled_dow_local', sa.SmallInteger(), nullable=False),
    sa.Column('estimated_departure_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_departure_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_arrival_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_arrival_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_arrival_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'BOARDING', 'DELAYED', 'DEPARTED', 'ARRIVED', 'CANCELLED', 'DIVERTED', 'UNKNOWN', name='flight_status'), nullable=False),
    sa.Column('delay_minutes', sa.Integer(), nullable=True),
    sa.Column('arrival_delay_minutes', sa.Integer(), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('is_diverted', sa.Boolean(), nullable=False),
    sa.Column('terminal', sa.String(length=16), nullable=True),
    sa.Column('gate', sa.String(length=16), nullable=True),
    sa.Column('aircraft_type', sa.String(length=64), nullable=True),
    sa.Column('aircraft_registration', sa.String(length=16), nullable=True),
    sa.Column('is_codeshare', sa.Boolean(), nullable=False),
    sa.Column('codeshare_of', sa.String(length=10), nullable=True),
    sa.Column('data_source', sa.String(length=40), nullable=False),
    sa.Column('is_mock', sa.Boolean(), nullable=False),
    sa.Column('data_quality', sa.Enum('OK', 'PARTIAL', 'STALE', 'UNRELIABLE', name='data_quality'), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('observation_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('delay_minutes IS NULL OR delay_minutes >= -180', name=op.f('ck_flights_delay_minutes_sane')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_flights')),
    sa.UniqueConstraint('flight_number', 'origin_iata', 'destination_iata', 'flight_date_local', name='uq_flights_identity')
    )
    op.create_index(op.f('ix_flights_airline_iata'), 'flights', ['airline_iata'], unique=False)
    op.create_index('ix_flights_airline_status', 'flights', ['airline_iata', 'status'], unique=False)
    op.create_index('ix_flights_date_local', 'flights', ['flight_date_local'], unique=False)
    op.create_index(op.f('ix_flights_flight_iata'), 'flights', ['flight_iata'], unique=False)
    op.create_index('ix_flights_flight_number', 'flights', ['flight_number'], unique=False)
    op.create_index(op.f('ix_flights_is_mock'), 'flights', ['is_mock'], unique=False)
    op.create_index(op.f('ix_flights_last_seen_at'), 'flights', ['last_seen_at'], unique=False)
    op.create_index('ix_flights_local_hour', 'flights', ['scheduled_hour_local'], unique=False)
    op.create_index('ix_flights_route_sched', 'flights', ['origin_iata', 'destination_iata', 'scheduled_departure_utc'], unique=False)
    op.create_index('ix_flights_sched_dep', 'flights', ['scheduled_departure_utc'], unique=False)
    op.create_index('ix_flights_status', 'flights', ['status'], unique=False)
    op.create_table('hourly_statistics',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('hour_local', sa.SmallInteger(), nullable=False),
    sa.Column('scope', sa.Enum('OVERALL', 'ROUTE', 'AIRLINE', 'FLIGHT', 'PERIOD', 'DOW', 'ROUTE_PERIOD', 'ROUTE_AIRLINE', name='stat_scope'), nullable=False),
    sa.Column('scope_key', sa.String(length=40), nullable=False),
    sa.Column('route', sa.String(length=8), nullable=True),
    sa.Column('total_flights', sa.Integer(), nullable=False),
    sa.Column('completed_flights', sa.Integer(), nullable=False),
    sa.Column('cancelled_flights', sa.Integer(), nullable=False),
    sa.Column('diverted_flights', sa.Integer(), nullable=False),
    sa.Column('delayed_flights', sa.Integer(), nullable=False),
    sa.Column('on_time_flights', sa.Integer(), nullable=False),
    sa.Column('unknown_flights', sa.Integer(), nullable=False),
    sa.Column('delayed_gt_15', sa.Integer(), nullable=False),
    sa.Column('delayed_gt_30', sa.Integer(), nullable=False),
    sa.Column('delayed_gt_60', sa.Integer(), nullable=False),
    sa.Column('delayed_gt_120', sa.Integer(), nullable=False),
    sa.Column('avg_delay_minutes', sa.Float(), nullable=True),
    sa.Column('median_delay_minutes', sa.Float(), nullable=True),
    sa.Column('p90_delay_minutes', sa.Float(), nullable=True),
    sa.Column('max_delay_minutes', sa.Integer(), nullable=True),
    sa.Column('cancellation_rate', sa.Float(), nullable=True),
    sa.Column('delay_rate', sa.Float(), nullable=True),
    sa.Column('on_time_rate', sa.Float(), nullable=True),
    sa.Column('severe_delay_rate', sa.Float(), nullable=True),
    sa.Column('reliability_score', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hourly_statistics')),
    sa.UniqueConstraint('stat_date', 'hour_local', 'scope', 'scope_key', name='uq_hourly_stat_dimension')
    )
    op.create_index('ix_hourly_date', 'hourly_statistics', ['stat_date'], unique=False)
    op.create_index('ix_hourly_hour', 'hourly_statistics', ['hour_local'], unique=False)
    op.create_index('ix_hourly_scope_date', 'hourly_statistics', ['scope', 'scope_key', 'stat_date'], unique=False)
    op.create_table('provider_health',
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('is_healthy', sa.Boolean(), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('total_calls', sa.BigInteger(), nullable=False),
    sa.Column('total_failures', sa.BigInteger(), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_latency_ms', sa.Float(), nullable=True),
    sa.Column('cooldown_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('provider', name=op.f('pk_provider_health'))
    )
    op.create_table('sent_alerts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('alert_type', sa.Enum('CANCELLATION', 'DELAY_THRESHOLD', 'ROUTE_DISRUPTION', 'HOURLY_REPORT', 'DAILY_REPORT', 'PROVIDER_OUTAGE', name='alert_type'), nullable=False),
    sa.Column('dedup_key', sa.String(length=200), nullable=False),
    sa.Column('flight_id', sa.BigInteger(), nullable=True),
    sa.Column('chat_id', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sent_alerts')),
    sa.UniqueConstraint('dedup_key', name='uq_sent_alerts_dedup_key')
    )
    op.create_index('ix_alerts_type_time', 'sent_alerts', ['alert_type', 'sent_at'], unique=False)
    op.create_table('flight_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('flight_id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.Enum('FIRST_SEEN', 'STATUS_CHANGED', 'DELAY_INCREASED', 'DELAY_DECREASED', 'CANCELLED', 'DIVERTED', 'DEPARTED', 'ARRIVED', 'GATE_CHANGED', 'TERMINAL_CHANGED', 'SCHEDULE_CHANGED', 'WENT_STALE', name='flight_event_type'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('previous_value', sa.String(length=120), nullable=True),
    sa.Column('new_value', sa.String(length=120), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('data_source', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], name=op.f('fk_flight_events_flight_id_flights'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_flight_events'))
    )
    op.create_index('ix_events_flight_time', 'flight_events', ['flight_id', 'occurred_at'], unique=False)
    op.create_index('ix_events_type_time', 'flight_events', ['event_type', 'occurred_at'], unique=False)
    op.create_table('flight_observations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('flight_id', sa.BigInteger(), nullable=False),
    sa.Column('collection_run_id', sa.BigInteger(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'BOARDING', 'DELAYED', 'DEPARTED', 'ARRIVED', 'CANCELLED', 'DIVERTED', 'UNKNOWN', name='flight_status'), nullable=False),
    sa.Column('raw_status', sa.String(length=64), nullable=True),
    sa.Column('delay_minutes', sa.Integer(), nullable=True),
    sa.Column('arrival_delay_minutes', sa.Integer(), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('is_diverted', sa.Boolean(), nullable=False),
    sa.Column('scheduled_departure_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_departure_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_departure_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_arrival_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_arrival_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_arrival_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('terminal', sa.String(length=16), nullable=True),
    sa.Column('gate', sa.String(length=16), nullable=True),
    sa.Column('aircraft_type', sa.String(length=64), nullable=True),
    sa.Column('aircraft_registration', sa.String(length=16), nullable=True),
    sa.Column('data_source', sa.String(length=40), nullable=False),
    sa.Column('data_quality', sa.Enum('OK', 'PARTIAL', 'STALE', 'UNRELIABLE', name='data_quality'), nullable=False),
    sa.ForeignKeyConstraint(['collection_run_id'], ['collection_runs.id'], name=op.f('fk_flight_observations_collection_run_id_collection_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], name=op.f('fk_flight_observations_flight_id_flights'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_flight_observations')),
    sa.UniqueConstraint('flight_id', 'collection_run_id', 'data_source', name='uq_observation_per_run')
    )
    op.create_index('ix_obs_flight_time', 'flight_observations', ['flight_id', 'observed_at'], unique=False)
    op.create_index('ix_obs_observed_at', 'flight_observations', ['observed_at'], unique=False)
    op.create_index('ix_obs_source', 'flight_observations', ['data_source'], unique=False)
    op.create_index('ix_obs_status', 'flight_observations', ['status'], unique=False)
    # ### end Alembic commands ###


    # ------------------------------------------------------------------ seed
    # Reference rows for the airports this deployment monitors. Kept in the
    # migration so a fresh database is queryable before the first collection.
    op.bulk_insert(
        sa.table(
            "airports",
            sa.column("iata", sa.String),
            sa.column("icao", sa.String),
            sa.column("name", sa.String),
            sa.column("city", sa.String),
            sa.column("country", sa.String),
            sa.column("timezone", sa.String),
            sa.column("latitude", sa.Float),
            sa.column("longitude", sa.Float),
        ),
        [
            {
                "iata": "IST",
                "icao": "LTFM",
                "name": "Istanbul Airport",
                "city": "Istanbul",
                "country": "Turkey",
                "timezone": "Europe/Istanbul",
                "latitude": 41.2753,
                "longitude": 28.7519,
            },
            {
                "iata": "IKA",
                "icao": "OIIE",
                "name": "Imam Khomeini International Airport",
                "city": "Tehran",
                "country": "Iran",
                "timezone": "Asia/Tehran",
                "latitude": 35.4161,
                "longitude": 51.1522,
            },
            {
                "iata": "MHD",
                "icao": "OIMM",
                "name": "Mashhad International Airport",
                "city": "Mashhad",
                "country": "Iran",
                "timezone": "Asia/Tehran",
                "latitude": 36.2352,
                "longitude": 59.6410,
            },
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_obs_status', table_name='flight_observations')
    op.drop_index('ix_obs_source', table_name='flight_observations')
    op.drop_index('ix_obs_observed_at', table_name='flight_observations')
    op.drop_index('ix_obs_flight_time', table_name='flight_observations')
    op.drop_table('flight_observations')
    op.drop_index('ix_events_type_time', table_name='flight_events')
    op.drop_index('ix_events_flight_time', table_name='flight_events')
    op.drop_table('flight_events')
    op.drop_index('ix_alerts_type_time', table_name='sent_alerts')
    op.drop_table('sent_alerts')
    op.drop_table('provider_health')
    op.drop_index('ix_hourly_scope_date', table_name='hourly_statistics')
    op.drop_index('ix_hourly_hour', table_name='hourly_statistics')
    op.drop_index('ix_hourly_date', table_name='hourly_statistics')
    op.drop_table('hourly_statistics')
    op.drop_index('ix_flights_status', table_name='flights')
    op.drop_index('ix_flights_sched_dep', table_name='flights')
    op.drop_index('ix_flights_route_sched', table_name='flights')
    op.drop_index('ix_flights_local_hour', table_name='flights')
    op.drop_index(op.f('ix_flights_last_seen_at'), table_name='flights')
    op.drop_index(op.f('ix_flights_is_mock'), table_name='flights')
    op.drop_index('ix_flights_flight_number', table_name='flights')
    op.drop_index(op.f('ix_flights_flight_iata'), table_name='flights')
    op.drop_index('ix_flights_date_local', table_name='flights')
    op.drop_index('ix_flights_airline_status', table_name='flights')
    op.drop_index(op.f('ix_flights_airline_iata'), table_name='flights')
    op.drop_table('flights')
    op.drop_index('ix_daily_scope_date', table_name='daily_statistics')
    op.drop_index('ix_daily_route', table_name='daily_statistics')
    op.drop_index('ix_daily_date', table_name='daily_statistics')
    op.drop_table('daily_statistics')
    op.drop_index('ix_runs_started', table_name='collection_runs')
    op.drop_table('collection_runs')
    op.drop_index(op.f('ix_airports_icao'), table_name='airports')
    op.drop_table('airports')
    op.drop_index(op.f('ix_airlines_icao'), table_name='airlines')
    op.drop_index(op.f('ix_airlines_iata'), table_name='airlines')
    op.drop_table('airlines')
    # ### end Alembic commands ###
